<div id="perso" class="divShow" hidden>
    <h1>Identité</h1>
    <table>
    <thead>
            <tr>
                <th>Pseudo</th>
                <th>Nature</th>
                <th>Attitude</th>
                <th>Cabale</th>
                <th>Essence</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><input id='pseudo' type="text" placeholder="Pseudo" name="Pseudo" required></td>
                <td><input id='pseudo' type="text" placeholder="Nature" name="Nature" required></td>
                <td><input id='pseudo' type="text" placeholder="Attitude" name="Attitude" required></td>
                <td><input id='pseudo' type="text" placeholder="Cabale" name="Cabale" required></td>
                <td><input id='pseudo' type="text" placeholder="Essence" name="Essence" required></td>
            </tr>
        </tbody>
    </table>
    <h1>Attribue</h1>
    <table>
    <thead>
            <tr>
                <th>Physique</th>
                <th>Social</th>
                <th>Inteligence</th>
                <th>Magie</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    Force 
                    </br>
                    Dexterite
                    </br>
                    Vigueur
                </td>
                <td>
                    Charisme 
                    </br>
                    Manipulation
                    </br>
                    Apparance
                </td>
                <td>
                    Perception 
                    </br>
                    Memoire
                    </br>
                    Logique
                </td>
                <td>
                    Puissance 
                    </br>
                    Dexterite
                    </br>
                    Vigueur
                </td>
            </tr>
        </tbody>
    </table>
    <h1>Capacité</h1>
    <table>
    <thead>
            <tr>
                <th>Talent</th>
                <th>Competence</th>
                <th>Connaissance</th>
                <th>Sort</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    Bagarre 
                    </br>
                    Conscience
                    </br>
                    Esquive
                    </br>
                    Expression
                    </br>
                    Intimidation
                    </br>
                    Intuition
                    </br>
                    Courses
                    </br>
                    Natation
                    </br>
                    Escalade
                    </br>
                    Subterfuge
                    </br>
                    Vigilance
                    </br>
                    Orientation
                    </br>
                    Parade
                </td>
                <td>
                    Armes à feu 
                    </br>
                    Commandement
                    </br>
                    Equitation
                    </br>
                    Cocher
                    </br>
                    Etiquette
                    </br>
                    Furtivité
                    </br>
                    Médiation
                    </br>
                    Mélée
                    </br>
                    Arme de jet
                    </br>
                    Archerie
                    </br>
                    Forgeron
                    </br>
                    Tailleur
                    </br>
                    Cocher
                    </br>
                    Enchanteur
                    </br>
                    Dresseur
                </td>
                <td>
                    Cosmologie 
                    </br>
                    Culture
                    </br>
                    Droit
                    </br>
                    Enigmes
                    </br>
                    Investigation
                    </br>
                    Linguistique
                    </br>
                    Médecine
                    </br>
                    Occulte
                    </br>
                    Sciences
                    </br>
                    Herboriste
                    </br>
                    Alphabétisation
                </td>
                <td>
                </td>
            </tr>
        </tbody>
    </table>
    <h1>Historique</h1>
    <h1>Atout/Handicap</h1>
    <h1>Background</h1>
    <h1>Equipement</h1>
</div>

